server:
  servlet:
    context-path: /snail-okr
snail:
  okr:
    redis:
      host: 127.0.0.1
      port: 6379
      password: seblong
      maxTotal: 32
      maxIdle: 8
      testOnIdle: true
    mongodb:
      url: mongodb://root:seblong2015@127.0.0.1:27017/seblong?maxPoolSize=3000&waitQueueMultiple=500&waitQueueTimeoutMS=5000
    wechat:
      appid: ww8d0e994b898e7746
      secret: hGd_QdLN2vPcaU4OfrGete4cQQKIPWHlZQcEEHzEXP0
      redirectUri: https://api.snailsleep.net/OKRSaasA/index
      authUrl: https://open.weixin.qq.com/connect/oauth2/authorize
swagger:
  enabled: true